# Project: Project5
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o ../../程设/ACLLib-master/ACLLib-master/src/acllib.o
LINKOBJ  = main.o ../../程设/ACLLib-master/ACLLib-master/src/acllib.o
LIBS     = -L"E:/devcpp/Dev-Cpp/MinGW64/lib" -L"E:/devcpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows ../../devcpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libwinmm.a ../../devcpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/liboleaut32.a ../../devcpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libgdi32.a ../../devcpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libmsimg32.a ../../devcpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libuuid.a ../../devcpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libole32.a ../../devcpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libuser32.a ../../devcpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libkernel32.a -g3
INCS     = -I"E:/devcpp/Dev-Cpp/MinGW64/include" -I"E:/devcpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/devcpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/devcpp/Dev-Cpp/MinGW64/include" -I"E:/devcpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/devcpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/devcpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = game.exe
CXXFLAGS = $(CXXINCS) -std=gnu99 -g3
CFLAGS   = $(INCS) -std=gnu99 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

../../程设/ACLLib-master/ACLLib-master/src/acllib.o: ../../程设/ACLLib-master/ACLLib-master/src/acllib.c
	$(CC) -c ../../程设/ACLLib-master/ACLLib-master/src/acllib.c -o ../../程设/ACLLib-master/ACLLib-master/src/acllib.o $(CFLAGS)
